use 4 spaces for tabs

diff --git a/essentials/initramfs/mkinitramfs b/essentials/initramfs/mkinitramfs
--- a/essentials/initramfs/mkinitramfs
+++ b/essentials/initramfs/mkinitramfs
@@ -2,23 +2,22 @@
 # This file based in part on the mkinitrafms script for the LFS LiveCD
 # written by Alexander E. Patrakov and Jeremy Huntwork.
 
-copy()
-{
-  local file
+copy() {
+    local file
 
-  if [ "$2" == "lib" ]; then
-    file=$(PATH=/lib:/usr/lib type -p $1)
-  else
-    file=$(type -p $1)
-  fi
+    if [ "$2" == "lib" ]; then
+        file=$(PATH=/lib:/usr/lib type -p $1)
+    else
+        file=$(type -p $1)
+    fi
 
-  if [ -n $file ] ; then
-    cp $file $WDIR/$2
-  else
-    echo "Missing required file: $1 for directory $2"
-    rm -rf $WDIR
-    exit 1
-  fi
+    if [ -n $file ] ; then
+        cp $file $WDIR/$2
+    else
+        echo "Missing required file: $1 for directory $2"
+        rm -rf $WDIR
+        exit 1
+    fi
 }
 
 INITRAMFS_FILE=initrd.img
@@ -55,7 +54,7 @@ mknod -m 664 $WDIR/dev/null    c 1 3
 cp -a /dev/mapper/control $WDIR/dev/mapper
 
 for file in $(find /etc/udev/rules.d/ -type f) ; do
-  cp $file $WDIR/etc/udev/rules.d
+    cp $file $WDIR/etc/udev/rules.d
 done
 
 # Install any firmware present
@@ -66,18 +65,18 @@ install -m0755 $DATADIR/$INITIN $WDIR/init
 
 # Install basic binaries
 for f in $binfiles ; do
-  ldd /bin/$f | sed "s/\t//" | cut -d " " -f1 >> $unsorted
-  copy $f bin
+    ldd /bin/$f | sed "s/\t//" | cut -d " " -f1 >> $unsorted
+    copy $f bin
 done
 
 for f in $sbinfiles ; do
-  ldd /sbin/$f | sed "s/\t//" | cut -d " " -f1 >> $unsorted
-  copy $f sbin
+    ldd /sbin/$f | sed "s/\t//" | cut -d " " -f1 >> $unsorted
+    copy $f sbin
 done
 
 for f in $usrsbinfiles ; do
-  ldd /usr/sbin/$f | sed "s/\t//" | cut -d " " -f1 >> $unsorted
-  copy $f sbin
+    ldd /usr/sbin/$f | sed "s/\t//" | cut -d " " -f1 >> $unsorted
+    copy $f sbin
 done
 
 # Add udevd libraries if not in /sbin
@@ -85,11 +84,11 @@ ldd /usr/bin/udevd | sed "s/\t//" | cut -d " " -f1 >> $unsorted
 
 # Install libraries
 sort $unsorted | uniq | grep -v fakeroot | while read library ; do
-  if [ "$library" == "linux-vdso.so.1" ] ||
-     [ "$library" == "linux-gate.so.1" ]; then
-    continue
-  fi
-  copy $library lib
+    if [ "$library" == "linux-vdso.so.1" ] ||
+        [ "$library" == "linux-gate.so.1" ]; then
+        continue
+    fi
+    copy $library lib
 done
 
 cp -a /usr/lib/udev $WDIR/lib
